### ISSUE TITLE
GroDecoder is crashing with example files

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#58]
With the last version of Grodecoder on the main branch, I got this error:

```bash
python grodecoder.py --input data/examples/1BRS.gro
2024-07-01 17:49:25.301 | INFO     | __main__:remove_hydrogene:745 - Found 146,910 atoms in data/examples/1BRS.gro
2024-07-01 17:49:25.301 | INFO     | __main__:remove_hydrogene:748 - Removing hydrogen atoms...
[...]
2024-07-01 17:50:43.289 | INFO     | __main__:print_graph_inventory:656 - Molecule 5 ----------------
Traceback (most recent call last):
  File "[...]/grodecoder.git/grodecoder.py", line 1485, in <module>
    main(
  File "[...]/grodecoder.git/grodecoder.py", line 1332, in main
    print_graph_inventory(graph_count_dict)
  File "[...]/grodecoder.git/grodecoder.py", line 661, in print_graph_inventory
    (_, res_id_interval, _, _, name, count, _, _, _) = key.values()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 9, got 8)

```

Could you have a look @KarinDuong ?

**Comment by pierrepo** [comment]
It looks like the bug has been introduced in the very last commit:
https://github.com/pierrepo/grodecoder/commit/006e51ce9c75cfa13f789d14cba3b5c3ee9d3653
